### ISSUE TITLE
Explizites Tracking der Start/Ende-Zeiten für Termine

### ISSUE THREAD

**Issue by penguineer** [JensWinter/tech-events-magdeburg#70]
Für ical-Events in #3 und #13 benötigen wir formale Start-/Ende-Zeiten, d.h. die Daten sollten um entsprechende Felder erweitert werden, anstatt hier Freitext-Angaben vorzusehen.

**Comment by penguineer** [comment]
Mir allen ad-hoc zwei Lösungen ein:

1. Explizite Angabe von Start und Ende: Das entspricht den Daten, die wir im Ical wahrscheinlich brauchen, aber dann müssten wir validieren, ob die Angaben sinnvoll sind.
2. Angabe von Start-Zeit und Dauer, was die Validierung vereinfacht. Eventuell kann ical auch mit der Dauer eines Termins arbeiten.

Außerdem ist es sinnvoll, ganztägige Termine vorzusehen.

**Comment by penguineer** [comment]
Wegen möglicher Änderungskonflikte sollte dieses Issue erst nach #66 und #69 bearbeitet werden.

**Comment by penguineer** [comment]
Ein Kalendereintrag könnte so aussehen:

```yaml
---
date: "2023-06-12"
start: 18:30
duration: 1:30
allday: false
org: "SAP Stammtisch Magdeburg"
email: "mail@example.com"
title: "#28 - Wo geht es lang ... für IT Betrieb und Service?"
location: "SAP UCC, Universitätsplatz 12"
url_title: "Infos zum Termin"
url: "https://sapstammtisch.github.io/Magdeburg/"
---
```

Mit diesem Template könnte man dann ein Ical-Event generieren.

```jinja
---
layout: null
---
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
UID:{{ page.url | absolute_url | sha1 }}
DTSTAMP:{{ page.date | date_to_xmlschema }}
ORGANIZER;CN={{ page.org }}:MAILTO:{{ page.email }}
{% if page.allday %}
DTSTART;VALUE=DATE:{{ page.date | date: "%Y%m%d" }}
DTEND;VALUE=DATE:{{ page.date | date: "%Y%m%d" | plus: 1 }}
{% else %}
DTSTART:{{ page.date | date: "%Y%m%d" }}T{{ page.start | replace: ":", "" }}00Z
DURATION:PT{{ page.duration | replace: ":", "H" }}M
{% endif %}
SUMMARY:{{ page.title | escape }}
LOCATION:{{ page.location | escape }}
URL;VALUE=URI:{{ page.url | xml_escape }}
DESCRIPTION:{{ page.url_title | xml_escape }}
END:VEVENT
END:VCALENDAR
```

Die Zuordnung Titel-Beschreibung passt hier noch nicht. Dafür müssten wir uns nochmal Gedanken zur Formalisierung der Felder machen.
